DROP VIEW IF EXISTS audit_contact;
DROP TABLE IF EXISTS audit_contact;

CREATE VIEW audit_contact AS
SELECT
  audit_transaction,
  audit_operation,
  roid,
  id,
  clid,
  crid,
  createdate,
  updatedate,
  intpostalname,
  intpostalorg,
  intpostalstreet1,
  intpostalcity,
  intpostalsp,
  intpostalpc,
  intpostalcc,
  locpostalname,
  locpostalorg,
  locpostalstreet1,
  locpostalcity,
  locpostalsp,
  locpostalpc,
  locpostalcc,
  voice,
  fax,
  email,
  intpostalstreet2,
  intpostalstreet3,
  locpostalstreet2,
  locpostalstreet3,
  voicex,
  faxx
FROM dblink('dbname=registry user=coccauser password=coccauser', '
  SELECT
    audit_transaction,
    audit_operation,
    roid,
    id,
    clid,
    crid,
    createdate,
    updatedate,
    intpostalname,
    intpostalorg,
    intpostalstreet1,
    intpostalcity,
    intpostalsp,
    intpostalpc,
    intpostalcc,
    locpostalname,
    locpostalorg,
    locpostalstreet1,
    locpostalcity,
    locpostalsp,
    locpostalpc,
    locpostalcc,
    voice,
    fax,
    email,
    intpostalstreet2,
    intpostalstreet3,
    locpostalstreet2,
    locpostalstreet3,
    voicex,
    faxx
  FROM audit.contact
  WHERE COALESCE(updatedate, createdate) > (current_timestamp - interval ''2'' month)
') cocca (
  audit_transaction BIGINT,
  audit_operation   VARCHAR(1),
  roid              VARCHAR(89),
  id                VARCHAR(16),
  clid              VARCHAR(16),
  crid              VARCHAR(16),
  createdate        TIMESTAMP,
  updatedate        TIMESTAMP,
  intpostalname     VARCHAR(255),
  intpostalorg      VARCHAR(255),
  intpostalstreet1  VARCHAR(255),
  intpostalcity     VARCHAR(255),
  intpostalsp       VARCHAR(255),
  intpostalpc       VARCHAR(255),
  intpostalcc       VARCHAR(255),
  locpostalname     VARCHAR(255),
  locpostalorg      VARCHAR(255),
  locpostalstreet1  VARCHAR(255),
  locpostalcity     VARCHAR(255),
  locpostalsp       VARCHAR(255),
  locpostalpc       VARCHAR(255),
  locpostalcc       VARCHAR(255),
  voice             VARCHAR(64),
  fax               VARCHAR(64),
  email             VARCHAR(2048),
  intpostalstreet2  VARCHAR(255),
  intpostalstreet3  VARCHAR(255),
  locpostalstreet2  VARCHAR(255),
  locpostalstreet3  VARCHAR(255),
  voicex            VARCHAR(64),
  faxx              VARCHAR(64)
);