default: &default
  adapter: postgresql
  encoding: unicode
  username: coccaadmin
  password: coccaadmin

development:
  <<: *default
  database: cocca_development

test: &test
  <<: *default
  database: cocca_test

production:
  <<: *default
  database: cocca
  username: <%= ENV['COCCAAPI_DATABASE_USERNAME'] %>
  password: <%= ENV['COCCAAPI_DATABASE_PASSWORD'] %>

audit_cocca_db:
  adapter: postgresql
  pool: 25
  username: coccaadmin
  password: coccaadmin
  host: cocca-db.staging.local
  database: registry
  schema_search_path: "audit"

public_cocca_db:
  adapter: postgresql
  pool: 25
  username: coccaadmin
  password: coccaadmin
  host: cocca-db.staging.local
  database: registry
  schema_search_path: "public"